# In dòng chữ và xoay vòng
# Sử dụng hàm time.sleep của module time để dừng 1 chút mỗi lần xoay vòng
import time
print("\rCong hoa xa hoi chu nghia Viet Nam ", end = '\0')
time.sleep(1)
print("\rong hoa xa hoi chu nghia Viet Nam C", end = '\0')
time.sleep(1)
print("\rng hoa xa hoi chu nghia Viet Nam Co", end = '\0')
time.sleep(1)
print("\rg hoa xa hoi chu nghia Viet Nam Con", end = '\0')
time.sleep(1)
print("\r hoa xa hoi chu nghia Viet Nam Cong", end = '\0')
time.sleep(1)
print("\rhoa xa hoi chu nghia Viet Nam Cong ", end = '\0')
time.sleep(1)
print("\roa xa hoi chu nghia Viet Nam Cong h", end = '\0')
time.sleep(1)
print("\ra xa hoi chu nghia Viet Nam Cong ho", end = '\0')
time.sleep(1)
print("\r xa hoi chu nghia Viet Nam Cong hoa", end = '\0')
time.sleep(1)
print("\rxa hoi chu nghia Viet Nam Cong hoa ", end = '\0')
time.sleep(1)
print("\ra hoi chu nghia Viet Nam Cong hoa x", end = '\0')
time.sleep(1)
print("\r hoi chu nghia Viet Nam Cong hoa xa", end = '\0')
time.sleep(1)
print("\rhoi chu nghia Viet Nam Cong hoa xa ", end = '\0')
time.sleep(1)
print("\roi chu nghia Viet Nam Cong hoa xa h", end = '\0')
time.sleep(1)
print("\ri chu nghia Viet Nam Cong hoa xa ho", end = '\0')
time.sleep(1)
print("\r chu nghia Viet Nam Cong hoa xa hoi", end = '\0')
time.sleep(1)
print("\rchu nghia Viet Nam Cong hoa xa hoi ", end = '\0')
time.sleep(1)
print("\rhu nghia Viet Nam Cong hoa xa hoi c", end = '\0')
time.sleep(1)
print("\ru nghia Viet Nam Cong hoa xa hoi ch", end = '\0')
time.sleep(1)
print("\r nghia Viet Nam Cong hoa xa hoi chu", end = '\0')
time.sleep(1)
print("\rnghia Viet Nam Cong hoa xa hoi chu ", end = '\0')
time.sleep(1)
print("\rghia Viet Nam Cong hoa xa hoi chu n", end = '\0')
time.sleep(1)
print("\rhia Viet Nam Cong hoa xa hoi chu ng", end = '\0')
time.sleep(1)
print("\ria Viet Nam Cong hoa xa hoi chu ngh", end = '\0')
time.sleep(1)
print("\ra Viet Nam Cong hoa xa hoi chu nghi", end = '\0')
time.sleep(1)
print("\r Viet Nam Cong hoa xa hoi chu nghia", end = '\0')
time.sleep(1)
print("\rViet Nam Cong hoa xa hoi chu nghia ", end = '\0')
time.sleep(1)
print("\riet Nam Cong hoa xa hoi chu nghia V", end = '\0')
time.sleep(1)
print("\ret Nam Cong hoa xa hoi chu nghia Vi", end = '\0')
time.sleep(1)
print("\rt Nam Cong hoa xa hoi chu nghia Vie", end = '\0')
time.sleep(1)
print("\r Nam Cong hoa xa hoi chu nghia Viet", end = '\0')
time.sleep(1)
print("\rNam Cong hoa xa hoi chu nghia Viet ", end = '\0')
time.sleep(1)
print("\ram Cong hoa xa hoi chu nghia Viet N", end = '\0')
time.sleep(1)
print("\rm Cong hoa xa hoi chu nghia Viet Na", end = '\0')
time.sleep(1)
print("\r Cong hoa xa hoi chu nghia Viet Nam", end = '\0')
time.sleep(1)
print("\rCong hoa xa hoi chu nghia Viet Nam ", end = '\0')
time.sleep(1)