print("Hà Nội", "Việt Nam")
print("Hà Nội", "Việt Nam", sep = '')
print("Hà Nội", "Việt Nam", sep = '-')
print("Hà Nội", "Việt Nam", sep = '@')
print("Hà Nội", "Việt Nam", sep = '    ')
print("Hà Nội"); print("Việt Nam")
print("Hà Nội", end = ''); print("Việt Nam")
print("Hà Nội'")
print("Việt Nam'")